POST http://localhost:3001/api/notes
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYThjYjk4NzE3ZWExOTg4MzhiMThiYSIsInVzZXJuYW1lIjoiZGlsYW4iLCJpYXQiOjE2NzIwMjA5MjcsImV4cCI6MTY3MjYyNTcyN30.O-hmBI2CSUX60Hf8RBVJTYuQr94x1kmU_gFE_kV17Gc

{
   "content": "Esto es una nueva nota",
   "important": true
}



###


POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

 {
    "content": "Esto es una nueva nota" 
 }